//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Repository.DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.BookIssues = new HashSet<BookIssue>();
        }
    
        public int BookID { get; set; }
        public string BookName { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public int AutherID { get; set; }
        public int CategoryID { get; set; }
        public decimal Price { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual ICollection<BookIssue> BookIssues { get; set; }
        public virtual Category Category { get; set; }
    }
}
