//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Repository.DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookIssue
    {
        public int BookIssueID { get; set; }
        public int BookID { get; set; }
        public int UserID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<decimal> FineAmount { get; set; }
        public int IssuerID { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Book Book { get; set; }
    }
}
