//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Repository.DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResetLink
    {
        public int ResetID { get; set; }
        public int UserID { get; set; }
        public int RandomCode { get; set; }
    
        public virtual User User { get; set; }
    }
}
