//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Repository.DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BookIssues = new HashSet<BookIssue>();
            this.BookIssues1 = new HashSet<BookIssue>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmaildID { get; set; }
        public string Password { get; set; }
        public byte[] MobileNumber { get; set; }
        public string AddressOne { get; set; }
        public string AddressTwo { get; set; }
        public bool IsActive { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public int RoleID { get; set; }
    
        public virtual ICollection<BookIssue> BookIssues { get; set; }
        public virtual ICollection<BookIssue> BookIssues1 { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
